/*
 * Created on 2019-11-03 ( Date ISO 2019-11-03 - Time 08:43:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.upc.gmt.bean;

import java.io.Serializable;


/**
 * Java bean for entity "colorproducto" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class Colorproducto implements Serializable {
    private static final long serialVersionUID = 1L;

    private Integer idcolorproducto; // Integer // Id or Primary Key

    private String color;  // String
    private String idestado;  // String

    /**
     * Default constructor
     */
    public Colorproducto() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------

    /**
     * Set the "idcolorproducto" field value
     * This field is mapped on the database column "IdColorProducto" ( type "INT", NotNull : true )
     *
     * @param idcolorproducto
     */
    public void setIdcolorproducto(Integer idcolorproducto) {
        this.idcolorproducto = idcolorproducto;
    }

    /**
     * Get the "idcolorproducto" field value
     * This field is mapped on the database column "IdColorProducto" ( type "INT", NotNull : true )
     *
     * @return the field value
     */
    public Integer getIdcolorproducto() {
        return this.idcolorproducto;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "color" field value
     * This field is mapped on the database column "Color" ( type "VARCHAR", NotNull : false )
     *
     * @param color
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Get the "color" field value
     * This field is mapped on the database column "Color" ( type "VARCHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getColor() {
        return this.color;
    }

    /**
     * Set the "idestado" field value
     * This field is mapped on the database column "IdEstado" ( type "CHAR", NotNull : false )
     *
     * @param idestado
     */
    public void setIdestado(String idestado) {
        this.idestado = idestado;
    }

    /**
     * Get the "idestado" field value
     * This field is mapped on the database column "IdEstado" ( type "CHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getIdestado() {
        return this.idestado;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(idcolorproducto);
        sb.append("|");
        sb.append(color);
        sb.append("|");
        sb.append(idestado);
        return sb.toString();
    }


}
