/*
 * Created on 2019-11-03 ( Date ISO 2019-11-03 - Time 08:43:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.upc.gmt.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for entity "empleado" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class Empleado implements Serializable {
    private static final long serialVersionUID = 1L;

    private String codusuario; // String // Id or Primary Key

    private String password;  // String
    private String nombre;  // String

    private Date fechacreacion;  // Date
    private String correoelectronico;  // String
    private String estado;  // String
    private Integer idtipousuario;  // Integer

    /**
     * Default constructor
     */
    public Empleado() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------

    /**
     * Set the "codusuario" field value
     * This field is mapped on the database column "CodUsuario" ( type "CHAR", NotNull : true )
     *
     * @param codusuario
     */
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }

    /**
     * Get the "codusuario" field value
     * This field is mapped on the database column "CodUsuario" ( type "CHAR", NotNull : true )
     *
     * @return the field value
     */
    public String getCodusuario() {
        return this.codusuario;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "password" field value
     * This field is mapped on the database column "Password" ( type "VARCHAR", NotNull : false )
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get the "password" field value
     * This field is mapped on the database column "Password" ( type "VARCHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "Nombre" ( type "VARCHAR", NotNull : true )
     *
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "Nombre" ( type "VARCHAR", NotNull : true )
     *
     * @return the field value
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Set the "fechacreacion" field value
     * This field is mapped on the database column "FechaCreacion" ( type "DATE", NotNull : false )
     *
     * @param fechacreacion
     */
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    /**
     * Get the "fechacreacion" field value
     * This field is mapped on the database column "FechaCreacion" ( type "DATE", NotNull : false )
     *
     * @return the field value
     */
    public Date getFechacreacion() {
        return this.fechacreacion;
    }

    /**
     * Set the "correoelectronico" field value
     * This field is mapped on the database column "CorreoElectronico" ( type "VARCHAR", NotNull : false )
     *
     * @param correoelectronico
     */
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }

    /**
     * Get the "correoelectronico" field value
     * This field is mapped on the database column "CorreoElectronico" ( type "VARCHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }

    /**
     * Set the "estado" field value
     * This field is mapped on the database column "Estado" ( type "CHAR", NotNull : false )
     *
     * @param estado
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Get the "estado" field value
     * This field is mapped on the database column "Estado" ( type "CHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getEstado() {
        return this.estado;
    }

    /**
     * Set the "idtipousuario" field value
     * This field is mapped on the database column "IdTipoUsuario" ( type "INT", NotNull : true )
     *
     * @param idtipousuario
     */
    public void setIdtipousuario(Integer idtipousuario) {
        this.idtipousuario = idtipousuario;
    }

    /**
     * Get the "idtipousuario" field value
     * This field is mapped on the database column "IdTipoUsuario" ( type "INT", NotNull : true )
     *
     * @return the field value
     */
    public Integer getIdtipousuario() {
        return this.idtipousuario;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(codusuario);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(fechacreacion);
        sb.append("|");
        sb.append(correoelectronico);
        sb.append("|");
        sb.append(estado);
        sb.append("|");
        sb.append(idtipousuario);
        return sb.toString();
    }


}
