/*
 * Created on 2019-11-03 ( Date ISO 2019-11-03 - Time 08:43:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.upc.gmt.bean;

import java.io.Serializable;


/**
 * Java bean for entity "temporada" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 * @author Telosys Tools Generator
 */
public class Temporada implements Serializable {
    private static final long serialVersionUID = 1L;

    private Integer idtemporada; // Integer // Id or Primary Key

    private String descripcion;  // String
    private String estado;  // String

    /**
     * Default constructor
     */
    public Temporada() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------

    /**
     * Set the "idtemporada" field value
     * This field is mapped on the database column "IdTemporada" ( type "INT", NotNull : true )
     *
     * @param idtemporada
     */
    public void setIdtemporada(Integer idtemporada) {
        this.idtemporada = idtemporada;
    }

    /**
     * Get the "idtemporada" field value
     * This field is mapped on the database column "IdTemporada" ( type "INT", NotNull : true )
     *
     * @return the field value
     */
    public Integer getIdtemporada() {
        return this.idtemporada;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "descripcion" field value
     * This field is mapped on the database column "Descripcion" ( type "VARCHAR", NotNull : false )
     *
     * @param descripcion
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * Get the "descripcion" field value
     * This field is mapped on the database column "Descripcion" ( type "VARCHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Set the "estado" field value
     * This field is mapped on the database column "Estado" ( type "CHAR", NotNull : false )
     *
     * @param estado
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Get the "estado" field value
     * This field is mapped on the database column "Estado" ( type "CHAR", NotNull : false )
     *
     * @return the field value
     */
    public String getEstado() {
        return this.estado;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(idtemporada);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(estado);
        return sb.toString();
    }


}
